name: multiple job in side jobs

on:
  workflow_dispatch:
    
jobs:
  job-1:
    runs-on: self-hosted
    steps:
      - run: echo "job A"
  job-2:
    runs-on: self-hosted 
    steps:
     - run: echo "job B"
