name: my first multiple steps

on:
  workflow_dispatch:

jobs:
  say-hello-bash:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "running bash script"
  say-python-script:
    runs-on: ubuntu-24.04
    steps:
      - run: print ("running python script")
        shell: python
        
